# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_iteam',
            unique_together=set([('title', 'deal_price')]),
        ),
    ]
