# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_auto_20190204_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_iteam',
            name='deal_price',
            field=models.CharField(max_length=300),
        ),
    ]
