# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_auto_20190204_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_iteam',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
